//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoneBookMVC.Models.DominModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Mobile { get; set; }
        public string PhoneNumber { get; set; }
        public string NationalCode { get; set; }
        public string OrgPos { get; set; }
    }
}
